{% set version = '0.3.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-forcats
  version: {{ version|replace("-", "_") }}

source:
  fn: forcats_{{ version }}.tar.gz
  url:
    - {{ cran_mirror }}/src/contrib/forcats_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/forcats/forcats_{{ version }}.tar.gz
  sha256: 95814610ec18b8a8830eba63751954387f9d21400d6ab40394ed0ff22c0cb657

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: covr, ggplot2, testthat
requirements:
  build:

  host:
    - r-base
    - r-magrittr
    - r-rlang
    - r-tibble

  run:
    - r-base
    - r-magrittr
    - r-rlang
    - r-tibble

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('forcats')"           # [not win]
    - "\"%R%\" -e \"library('forcats')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://forcats.tidyverse.org, https://github.com/tidyverse/forcats
  license: GPL-3
  summary: Helpers for reordering factor levels (including moving specified levels to front,
    ordering by first appearance, reversing, and randomly shuffling), and tools for
    modifying factor levels (including collapsing rare levels into other, 'anonymising',
    and manually 'recoding').
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: forcats
# Title: Tools for Working with Categorical Variables (Factors)
# Version: 0.3.0
# Authors@R: c( person("Hadley", "Wickham", , "hadley@rstudio.com", role = c("aut", "cre")), person("RStudio", role = c("cph", "fnd")) )
# Description: Helpers for reordering factor levels (including moving specified levels to front, ordering by first appearance, reversing, and randomly shuffling), and tools for modifying factor levels (including collapsing rare levels into other, 'anonymising', and manually 'recoding').
# License: GPL-3
# URL: http://forcats.tidyverse.org, https://github.com/tidyverse/forcats
# BugReports: https://github.com/tidyverse/forcats/issues
# Depends: R (>= 3.1)
# Imports: magrittr, rlang, tibble
# Suggests: covr, ggplot2, testthat
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2018-02-19 17:34:45 UTC; hadley
# Author: Hadley Wickham [aut, cre], RStudio [cph, fnd]
# Maintainer: Hadley Wickham <hadley@rstudio.com>
# Repository: CRAN
# Date/Publication: 2018-02-19 19:43:26 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
