# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_R=3.3.2
    - CONDA_R=3.4.1
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "kYGqS9Krm3vyXibH+NhWS6SDhqvMmTXYX8WF+6GuALsH8NHVpp9EkvldUl8I5hS9EOUAtxCYc23amJbxMcZ4ZPVtpVx5URuUfvjskYLwXHdSKhDwWkM5McZKtdmFlRcgViHPzd1fw602aLl+dtpQlvLvXXmKaYim3ChQJOSnpA50VRNd1vIjS0Hb8guJmE80bHCOEitRp5HFpk7RidnfE924xxgdI0ki4SfqHoTC1NgrJCoHOoii6xePfcE4rfWZ2z94SiXs2E5kOsyNy2VWYZsh+iJJGsQgEO44U9CxhfHQirpkLLvNpz1ZGPLY945lY/cO3FrYAD0D0kW+8NKt3eextxiQBVAWjn+k/mYhz/CGn/M/Y+Wbp30vo9WGvTQXj106Ezp+/QAsjAyCqpaLcQkPTZa8W5eRY43smvQQ5dYQcRqXrgtlAUHbTMnj5jSsor7e0yoR/4aNMh6TQB1Ev9tt2h8rE8QC/Se3qcTBaJgQP9+Ts4BAdmgwltMbk2bBTnFWuJCrL8UVUsTwEygQGtD4pYhEVX/kXOhnPCiWXLrKO7f9OQ0ovgORDgC7xewkxzMkwDjjVAKddSdZCI0NxhGO8I1jZLkBAObAVhj1+qy9yCwV1ahXEFo9hG+gI1AaG37xIoFPwI4xkcH3am0GnR0ppEUQzHPMG69h2pKwfic="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
