travis:
  secure:
    BINSTAR_TOKEN: ClsLCISzycm2st3W5ZZXPvUtrX8XaWc0cfohKDxrexHEbcoxLcetlzx/7c2KAP8qy1cD2IlZ05hmqQEAnGzm6Nsd21VPgzY9cF4izLqVvv8mdPLi53Fk9sSXTsBTKy7EQZ4MSBUvQCkTmnYxqIEmVyGOrG34DbESkuNnsPfKIQdLCVATL5krt7scZW/fw8YXowzTI8L5QBmfDHKL3sEo8diyvTstAg0jTvQXm7YucQjgP7crRnSMBwVPq46ocXbM7NdZiG7yje5m0NW+zMpgeSoqz7xd5DZ/VXgmh3iipNJbK5JPTKItZiWdmMo/YbrCAq0RoN2yHTO4bzMG4ix9latmkPPYwK4wFAOhEkm7ifVPZs3NVq7t4t/44fPFnMIz8uYXbl/hG0Z/5aK2f3btS8FoDEFusqGrU95T3zhUqQilYgbWhuKgZt51EcVsETYIumoTB2/ghH+jzpyCyBoJ1cesRSJ6noIBzFr8ZZwSJCFDxuKvwImuabKi4vU79EUemaEPXWW+/uZ5gfF14yT37IQulLwiyrVBSkvHTnQzLhL4ad4oXCwNfkUK6rypqiQJYSkKU8kmB/TUfQ0tJANGyKtnyKyDPdqyoDXQIA9teV9v6LRDp4ctr1OrSnX9A1N+7Xb9e9BBty7EJoycFp8KOIU7YWxB61CaaX7m8cxfCEU=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
