travis:
  secure:
    BINSTAR_TOKEN: NyevhXJXnv30j0ym20RWBWPR4kURt42TTZbgevqgAW8LFIKzCAUJgL2UGVefVAaFQbXJd2xTzSwLTz239E7PPGwuw7/HoMj0qHZDkA/+FY8b8xErNuXg/NP2bfjsJ4NCyk3/rWfARDTUDN3WlVwwoDHWvuBFgcbXoCvDKjCJWOVwhVhgesp8x6oPVWZaPAp1i8+ea6DLcZLh4KYlOc+zxgU7LYd/fVytaUNV4obreBKjaWzoew7xfbf8gIoNbvQmEhUzYSSgoVoPgPCgEOtOwhkfx64viXfEDYJCntEI5pXzdOrHF0TEDCixm2h/MG0odewA49tkXbTsD3BiQ27w16aVYikZthxngqISlSYSdX5GloGlyOMtALwPnATSa0N355nDcOJnQdM7E90B8UMEMuDjdSlUf8kH5+89+gWyDwqfJ0aT3S0NhTjvvv68edJg84U+At3F5tX1aWb1NkWbOs6C+z3uV9c9n2FxL1W0HvJfXxjJ0acldaeXUjaGwY6SUqyhJsHE1y7GepHRfBA8yNzaQsGBBg4N2oRYgYO7BBv4BC5jTXYciv7pYAKjfH4aG5zAx8GWPrm7U4ZMqitPOsp15yH91b94JFZZCokyW/cFUey3YQvncPd3Q3Qc16zjUsUGghRx/9gOC85Rmv34+8lsVUaCwsSfgNuj00svSvE=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
