travis:
  secure:
    BINSTAR_TOKEN: T4Yi/oS/upA5+mtZyC6IM/auhGgtaS0elQJ8lwiN6qmZVNPVw3g13oK2kgrRnCn+bAs93Q2qE+rKgMiUWJWYgCzki3T99uEzKYlVVuJBSEB//pzvwmiQw6zSytxWCDwbtT+38pQ5hFQXwJGcAtSGVwuBrLLErWveOMpDEohlW3IxMKZemKgJO2TwPTEjOozxQotktBPmzD21ZuMtXCPTpGMplpsaZo+h+TI6eW0lO/fqGiNGyBtXm84kEBw70VJOe63SD0qUNIoH2HYjpmjUB3pCnCKxqUVPWgS8gTVyIuVJy7hZilQBY3hxJpl34h4ce2QE0gBkPWVkNKosSOxg8TRGw2XtH9PZdkhQBO+wY/unL3MQed+QJbLLgzWMlAkfOpOzU9B1nl1C4NBwZPF1Yk4RrwV6H4OV5vp67g9Nih0M+mJjmPPQtqiKIFJIx7eSwFzfXAoiJM1H7Iy46xOBDM2TMffF27i9i40xac/E8IO1qEs74r1S/bNkKNaR6mfKEP+2gsRGvVj2yDJe7i86dGg6ARFn46hLoSipUBdldj0vNJ3xusxFG9jGcYdvCh0pSUGt3Z8dSChKuM/V+LB36shrRYgPwY5A5GZ/BzPLwVpnQ7/BsRSatg+tFlmFbIuRQKDlxlAhDiQNHEivK8RJ+/QyaamRyjV/r9jv5+8HfRU=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
