travis:
  secure:
    BINSTAR_TOKEN: kYGqS9Krm3vyXibH+NhWS6SDhqvMmTXYX8WF+6GuALsH8NHVpp9EkvldUl8I5hS9EOUAtxCYc23amJbxMcZ4ZPVtpVx5URuUfvjskYLwXHdSKhDwWkM5McZKtdmFlRcgViHPzd1fw602aLl+dtpQlvLvXXmKaYim3ChQJOSnpA50VRNd1vIjS0Hb8guJmE80bHCOEitRp5HFpk7RidnfE924xxgdI0ki4SfqHoTC1NgrJCoHOoii6xePfcE4rfWZ2z94SiXs2E5kOsyNy2VWYZsh+iJJGsQgEO44U9CxhfHQirpkLLvNpz1ZGPLY945lY/cO3FrYAD0D0kW+8NKt3eextxiQBVAWjn+k/mYhz/CGn/M/Y+Wbp30vo9WGvTQXj106Ezp+/QAsjAyCqpaLcQkPTZa8W5eRY43smvQQ5dYQcRqXrgtlAUHbTMnj5jSsor7e0yoR/4aNMh6TQB1Ev9tt2h8rE8QC/Se3qcTBaJgQP9+Ts4BAdmgwltMbk2bBTnFWuJCrL8UVUsTwEygQGtD4pYhEVX/kXOhnPCiWXLrKO7f9OQ0ovgORDgC7xewkxzMkwDjjVAKddSdZCI0NxhGO8I1jZLkBAObAVhj1+qy9yCwV1ahXEFo9hG+gI1AaG37xIoFPwI4xkcH3am0GnR0ppEUQzHPMG69h2pKwfic=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
